### DISCUSSION TITLE
Improvements looking for your help!

### DISCUSSION THREAD

**Discussion by fedebotu** [ai4co/rl4co#119] [General]
Would you like to contribute to RL4CO? 

This section is about improvements to the library that are not currently worked on by someone and are up for grabs. Feel free to comment if you would like to take on some task!

## TODOs

- [ ] Logging  hyperparameters with Wandb  <details><summary>Details</summary>
The logger on Wandb does not properly "unpack" keyword arguments, as can be seen here:
![image](https://github.com/ai4co/rl4co/assets/48984123/b4f46438-8366-44c2-9d65-700c69f486c4)
Normally, we should see some nested tab structure (like `optimizer_kwargs`:  1) ... 2)... ), which is also easier to search
We suspect it should not be hard to do - probably, the answer is somewhere in [here](https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.loggers.wandb.html)!
</details>

- [ ] MDAM beam search; refactoring with latest structure

- [ ] Pointer Network refactoring with latest structure

- [ ] Fix Google Colab notebook badges, e.g. [here](https://rl4co.readthedocs.io/en/latest/_collections/2-full-training.html)

## Done

- [x] Hydra documentation (thanks @LTluttmann!) <details>-<summary>Details</summary>
Currently, the Hydra documentation is a bit... ehehm ... lacking. Indeed, it is not easy to navigate the first time, no matter how much you will love it after. Would be great to have some documentation section (or even, say, some notebook) explaining how configurations are handled, along with tips and tricks
For example:
add new element to configuration with "+" (in this case, the `trainer.devices` argument): `python run.py experiment=routing/am +trainer.devices='[1]'`

</details>

> [!TIP]
> Do you have some feature you would like to add, such as a new policy, RL algorithm, problem and more? Just get in touch ;)

**Comment by LTluttmann** [comment]
Maybe this does not directly belong here, but regarding hydra I struggled when using the debug configuration, as this disables the wandb logger. This in turn leads to a failure in the hydra.run.dir, as this (by default) expects the wand logger. Maybe a better approach is to use:

```
hydra:
  run:
    dir: ${paths.log_dir}/${mode}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: ${paths.log_dir}/${mode}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}
```
as default and override this in the wand.yaml config as follows:

```
# @package _global_

# https://wandb.ai
logger:
  wandb:
    _target_: lightning.pytorch.loggers.wandb.WandbLogger
    # name: "" # name of the run (normally generated by wandb)
    save_dir: "${paths.output_dir}"
    offline: False
    id: null # pass correct id to resume experiment!
    anonymous: null # enable anonymous logging
    project: "rl4co"
    log_model: False # upload lightning ckpts
    prefix: "" # a string to put at the beginning of metric keys
    # entity: "" # set to name of your wandb team
    group: ""
    tags: []
    job_type: ""

hydra:
  run:
    dir: ${paths.log_dir}/${mode}/runs/${logger.wandb.group}/${logger.wandb.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: ${paths.log_dir}/${mode}/multiruns/${logger.wandb.group}/${logger.wandb.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}

```
What do you think? I could make a PR for this, maybe including some examples for how to use hydra properly.
